openapi: 3.0.0
info:
  title: Notification Service API
  description: API for managing user notifications
  version: 1.0.0
servers:
  - url: http://localhost:3002
    description: Local development server
paths:
  /:
    get:
      summary: Health check endpoint
      description: Returns a simple message indicating the service is running
      responses:
        '200':
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Notification Service is running"
  /notifications:
    post:
      summary: Create a new notification
      description: Creates a new notification for a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '201':
          description: Notification created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Cannot parse JSON"
    get:
      summary: Get all notifications
      description: Retrieves all notifications in the system
      responses:
        '200':
          description: List of notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
  /notifications/{id}:
    get:
      summary: Get a specific notification
      description: Retrieves a notification by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Notification not found"
  /notifications/user/{user_id}:
    get:
      summary: Get notifications for a user
      description: Retrieves all notifications for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of user notifications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notification'
  /notifications/{id}/read:
    put:
      summary: Mark notification as read
      description: Updates a notification's read status to true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Notification not found"
components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the notification
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_id:
          type: string
          description: ID of the user this notification belongs to
          example: "user123"
        type:
          type: string
          description: Type of the notification
          example: "alert"
        message:
          type: string
          description: Content of the notification
          example: "Your account has been updated"
        read:
          type: boolean
          description: Whether the notification has been read
          example: false
        timestamp:
          type: string
          description: When the notification was created
          example: "2024-04-07T12:00:00Z"
      required:
        - user_id
        - type
        - message 